2021-04-02 12:35:12,332               ERROR   :pymysql_DBHelper.py connectDatabase failed
2021-04-02 12:35:12,333               ERROR   :pymysql_DBHelper.py connectDatabase Exception (1045, "Access denied for user 'root'@'PC06' (using password: YES)")
2021-04-02 12:35:12,333               ERROR   :pymysql_DBHelper.py selectDict_finally_close_db failed: select * from settings
